CREATE TABLE SALES_REPORT_PART_KEY 
(
  ORDERID NUMBER(7) NOT NULL 
, PRODUCTID NUMBER(4) NOT NULL 
, PRODUCTCATEGORY VARCHAR2(26) NOT NULL 
, SALES NUMBER(11) NOT NULL 
, ORDER_DATE DATE NOT NULL 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    ORDERID 
  )
  ENABLE 
) 
PARTITION BY RANGE (ORDER_DATE) 
(
  PARTITION ORDERDATE2011 VALUES LESS THAN (to_date('31-DEC-2011', 'DD-MM-YYYY'))  
, PARTITION ORDERDATE2012 VALUES LESS THAN (to_date('31-DEC-2012', 'DD-MM-YYYY'))  
, PARTITION ORDERDATE2013 VALUES LESS THAN (to_date('31-DEC-2013', 'DD-MM-YYYY'))  
, PARTITION ORDEDATE2014 VALUES LESS THAN (to_date('31-DEC-2014', 'DD-MM-YYYY'))  
, PARTITION OTHER VALUES LESS THAN (MAXVALUE)  
);
