--------------------------------------------------------
--  File created - Thursday-April-12-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "LOAD_STAGING"."EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER(5,0), 
	"EMPLOYEE_NAME" VARCHAR2(100 BYTE), 
	"POSITION_TITLE" VARCHAR2(50 BYTE), 
	"PHONE_EXTENSION" VARCHAR2(10 BYTE), 
	"HIRE_DATE" DATE, 
	"OFFICE_NUMBER" VARCHAR2(5 BYTE), 
	"REPORTS_TO" NUMBER(4,0), 
	"YEAR_SALARY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGING" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOAD_STAGING"."EMPLOYEES_PK" ON "LOAD_STAGING"."EMPLOYEES" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGING" ;
--------------------------------------------------------
--  DDL for Trigger EMPLOYEES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "LOAD_STAGING"."EMPLOYEES_TRG" 
BEFORE INSERT ON EMPLOYEES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.EMPLOYEE_ID IS NULL THEN
      SELECT EMPLOYEES_SEQ.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "LOAD_STAGING"."EMPLOYEES_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "LOAD_STAGING"."EMPLOYEES" ADD CONSTRAINT "EMPLOYEES_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAGING"  ENABLE;
 
  ALTER TABLE "LOAD_STAGING"."EMPLOYEES" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "LOAD_STAGING"."EMPLOYEES" MODIFY ("EMPLOYEE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "LOAD_STAGING"."EMPLOYEES" MODIFY ("HIRE_DATE" NOT NULL ENABLE);
