--------------------------------------------------------
--  DDL for Table SALES_REPORT_PART
--------------------------------------------------------

  CREATE TABLE "PRODUCTION"."SALES_REPORT_PART_KEY" 
   (	"ORDERID" NUMBER(7,0), 
	"PRODUCTID" NUMBER(4,0), 
	"PRODUCTCATEGORY" VARCHAR2(26 BYTE), 
	"SALES" NUMBER(11,4), 
	"ORDER_DATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRODUCTION_DATA" 
  PARTITION BY RANGE ("ORDER_DATE") 
 (PARTITION "ORDERDATE2011"  VALUES LESS THAN (TO_DATE(' 2011-12-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRODUCTION_DATA" NOCOMPRESS , 
 PARTITION "ORDERDATE2012"  VALUES LESS THAN (TO_DATE(' 2012-12-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRODUCTION_DATA" NOCOMPRESS , 
 PARTITION "ORDERDATE2013"  VALUES LESS THAN (TO_DATE(' 2013-12-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRODUCTION_DATA" NOCOMPRESS , 
 PARTITION "ORDERDATE2014"  VALUES LESS THAN (TO_DATE(' 2014-12-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRODUCTION_DATA" NOCOMPRESS , 
 PARTITION "OTHER"  VALUES LESS THAN (MAXVALUE) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRODUCTION_DATA" NOCOMPRESS ) ;
--------------------------------------------------------
--  Constraints for Table SALES_REPORT_PART
--------------------------------------------------------

  ALTER TABLE "PRODUCTION"."SALES_REPORT_PART_KEY" MODIFY ("ORDER_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "PRODUCTION"."SALES_REPORT_PART_KEY" MODIFY ("ORDERID" NOT NULL ENABLE);

  ADD CONSTRAINT SALES_REPORT_PART_KEY_PK PRIMARY KEY (SALES_REPORT_ID ) ENABLE;

